### ISSUE TITLE
Where is train_val.prototxt?

### ISSUE THREAD

**Issue by wuqiangch** [KissyZhou/FaceAlignment_Multi-task#1]
Where is the train_val.prototxt? Thanks!!

**Comment by KissyZhou** [comment]
training file now available

**Comment by wuqiangch** [comment]
@KissyZhou Thanks! How to prepare the label in hd5 file. As every image has five labels :landmarks,smile ,pose,gender,glasses.I only know the sitiation of only one label.

**Comment by KissyZhou** [comment]
I think you should google/bing/baidu it.   like  "caffe hdf5"

**Comment by KissyZhou** [comment]
hdf5data allows labels to be a vector, then slice them in caffe by "Slice" layer

**Comment by wuqiangch** [comment]
@KissyZhou 图像像素值需要做归一化吗？比如都除以255等
